// flow-typed signature: 293399f13946177ffa18927005b21f25
// flow-typed version: <<STUB>>/@mars/heroku-js-runtime-env_v^3.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mars/heroku-js-runtime-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mars/heroku-js-runtime-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mars/heroku-js-runtime-env/test/development-test' {
  declare module.exports: any;
}

declare module '@mars/heroku-js-runtime-env/test/production-test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mars/heroku-js-runtime-env/index' {
  declare module.exports: $Exports<'@mars/heroku-js-runtime-env'>;
}
declare module '@mars/heroku-js-runtime-env/index.js' {
  declare module.exports: $Exports<'@mars/heroku-js-runtime-env'>;
}
declare module '@mars/heroku-js-runtime-env/test/development-test.js' {
  declare module.exports: $Exports<'@mars/heroku-js-runtime-env/test/development-test'>;
}
declare module '@mars/heroku-js-runtime-env/test/production-test.js' {
  declare module.exports: $Exports<'@mars/heroku-js-runtime-env/test/production-test'>;
}
